//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKMvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// 提问类型
    /// </summary>
    public partial class Problems_Type
    {
        /// <summary>
        /// 提问ID
        /// </summary>
        public int Problems_Type_Id { get; set; }
        /// <summary>
        /// 提问类型
        /// </summary>
        public string Problems_Type_Name { get; set; }
    }
}
